export const NATIVE_SOURCE_CONNECTION_COMMANDS = {
  activateReadwiseOnThisHost: 'activate_readwise_on_this_host',
  connectReadwiseApiFromClipboard: 'connect_readwise_api_from_clipboard',
  confirmSourceManagement: 'confirm_source_management',
  confirmWatchedFolderReconnect: 'confirm_watched_folder_reconnect',
  disconnectWatchedFolder: 'disconnect_watched_folder',
  disconnectExternalSearchFolder: 'disconnect_external_search_folder',
  disconnectReadwiseApi: 'disconnect_readwise_api',
  loadReadwiseHostAssignment: 'load_readwise_host_assignment',
  resolveReadwiseJoinDecision: 'resolve_readwise_join_decision',
  selectReadwiseImportDevice: 'select_readwise_import_device',
  loadReadwiseApiConnection: 'load_readwise_api_connection',
  loadReadwiseApiScheduleStatus: 'load_readwise_api_schedule_status',
  previewReadwiseSourceCutover: 'preview_readwise_source_cutover',
  runReadwiseSourceCutover: 'run_readwise_source_cutover',
  previewReadwiseIdentityBindings: 'preview_readwise_identity_bindings',
  confirmReadwiseIdentityBindings: 'confirm_readwise_identity_bindings',
  loadWatchedFolderBindings: 'load_watched_folder_bindings',
  previewWatchedFolderReconnect: 'preview_watched_folder_reconnect',
  previewExternalSearchFolderReconnect: 'preview_external_search_folder_reconnect',
  previewSourceManagement: 'preview_source_management',
  reconnectExternalSearchFolder: 'reconnect_external_search_folder',
  removeExternalSearchFolder: 'remove_external_search_folder',
  removeWatchedFolder: 'remove_watched_folder'
} as const;
